"""redesign election data model

Revision ID: 928be68b7f82
Revises: 466d11fd7338
Create Date: 2026-09-25 10:54:13.222869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '928be68b7f82'
down_revision: Union[str, Sequence[str], None] = '466d11fd7338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constituencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('constituency_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constituencies_code'), 'constituencies', ['code'], unique=True)
    op.create_index(op.f('ix_constituencies_constituency_type'), 'constituencies', ['constituency_type'], unique=False)
    op.create_index(op.f('ix_constituencies_id'), 'constituencies', ['id'], unique=False)
    op.create_index(op.f('ix_constituencies_name'), 'constituencies', ['name'], unique=False)
    op.create_table('elections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('election_type', sa.String(length=50), nullable=False),
    sa.Column('election_year', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('election_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('election_type', 'election_year', 'state', name='uq_election_type_year_state')
    )
    op.create_index(op.f('ix_elections_election_type'), 'elections', ['election_type'], unique=False)
    op.create_index(op.f('ix_elections_election_year'), 'elections', ['election_year'], unique=False)
    op.create_index(op.f('ix_elections_id'), 'elections', ['id'], unique=False)
    op.create_index(op.f('ix_elections_status'), 'elections', ['status'], unique=False)
    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('abbreviation', sa.String(length=20), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parties_abbreviation'), 'parties', ['abbreviation'], unique=True)
    op.create_index(op.f('ix_parties_id'), 'parties', ['id'], unique=False)
    op.create_index(op.f('ix_parties_name'), 'parties', ['name'], unique=True)
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('constituency_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('candidate_code', sa.String(length=50), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['constituency_id'], ['constituencies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('election_id', 'party_id', 'constituency_id', name='uq_candidate_election_party_constituency')
    )
    op.create_index(op.f('ix_candidates_candidate_code'), 'candidates', ['candidate_code'], unique=False)
    op.create_index(op.f('ix_candidates_constituency_id'), 'candidates', ['constituency_id'], unique=False)
    op.create_index(op.f('ix_candidates_election_id'), 'candidates', ['election_id'], unique=False)
    op.create_index(op.f('ix_candidates_id'), 'candidates', ['id'], unique=False)
    op.create_index(op.f('ix_candidates_party_id'), 'candidates', ['party_id'], unique=False)
    op.create_table('constituency_lgas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('constituency_id', sa.Integer(), nullable=False),
    sa.Column('lga_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['constituency_id'], ['constituencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lga_id'], ['lgas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('constituency_id', 'lga_id', name='uq_constituency_lga')
    )
    op.create_index(op.f('ix_constituency_lgas_constituency_id'), 'constituency_lgas', ['constituency_id'], unique=False)
    op.create_index(op.f('ix_constituency_lgas_id'), 'constituency_lgas', ['id'], unique=False)
    op.create_index(op.f('ix_constituency_lgas_lga_id'), 'constituency_lgas', ['lga_id'], unique=False)
    op.create_table('election_constituencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('constituency_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['constituency_id'], ['constituencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('election_id', 'constituency_id', name='uq_election_constituency')
    )
    op.create_index(op.f('ix_election_constituencies_constituency_id'), 'election_constituencies', ['constituency_id'], unique=False)
    op.create_index(op.f('ix_election_constituencies_election_id'), 'election_constituencies', ['election_id'], unique=False)
    op.create_index(op.f('ix_election_constituencies_id'), 'election_constituencies', ['id'], unique=False)
    op.create_table('election_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('polling_unit_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('total_valid_votes', sa.Integer(), nullable=False),
    sa.Column('rejected_votes', sa.Integer(), nullable=False),
    sa.Column('total_votes_cast', sa.Integer(), nullable=False),
    sa.Column('ec8a_photo_url', sa.String(length=500), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('rejected_votes >= 0', name='ck_result_rejected_votes_nonnegative'),
    sa.CheckConstraint('total_valid_votes >= 0', name='ck_result_valid_votes_nonnegative'),
    sa.CheckConstraint('total_votes_cast >= 0', name='ck_result_total_votes_nonnegative'),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['polling_unit_id'], ['polling_units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('election_id', 'polling_unit_id', name='uq_election_result_per_polling_unit')
    )
    op.create_index(op.f('ix_election_results_agent_id'), 'election_results', ['agent_id'], unique=False)
    op.create_index(op.f('ix_election_results_election_id'), 'election_results', ['election_id'], unique=False)
    op.create_index(op.f('ix_election_results_id'), 'election_results', ['id'], unique=False)
    op.create_index(op.f('ix_election_results_polling_unit_id'), 'election_results', ['polling_unit_id'], unique=False)
    op.create_index(op.f('ix_election_results_verification_status'), 'election_results', ['verification_status'], unique=False)
    op.create_table('election_result_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_result_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=False),
    sa.CheckConstraint('votes >= 0', name='ck_candidate_votes_nonnegative'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['election_result_id'], ['election_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('election_result_id', 'candidate_id', name='uq_result_candidate')
    )
    op.create_index(op.f('ix_election_result_votes_candidate_id'), 'election_result_votes', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_election_result_votes_election_result_id'), 'election_result_votes', ['election_result_id'], unique=False)
    op.create_index(op.f('ix_election_result_votes_id'), 'election_result_votes', ['id'], unique=False)
    op.drop_index(op.f('ix_vote_results_id'), table_name='vote_results')
    op.drop_index(op.f('ix_vote_results_polling_unit_id'), table_name='vote_results')
    op.drop_table('vote_results')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('polling_unit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pdp_votes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('apc_votes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nnpp_votes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lp_votes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('others_votes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_valid_votes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rejected_votes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_votes_cast', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ec8a_photo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('verification_status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('synced_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], name=op.f('vote_results_agent_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['polling_unit_id'], ['polling_units.id'], name=op.f('vote_results_polling_unit_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('vote_results_pkey'))
    )
    op.create_index(op.f('ix_vote_results_polling_unit_id'), 'vote_results', ['polling_unit_id'], unique=True)
    op.create_index(op.f('ix_vote_results_id'), 'vote_results', ['id'], unique=False)
    op.drop_index(op.f('ix_election_result_votes_id'), table_name='election_result_votes')
    op.drop_index(op.f('ix_election_result_votes_election_result_id'), table_name='election_result_votes')
    op.drop_index(op.f('ix_election_result_votes_candidate_id'), table_name='election_result_votes')
    op.drop_table('election_result_votes')
    op.drop_index(op.f('ix_election_results_verification_status'), table_name='election_results')
    op.drop_index(op.f('ix_election_results_polling_unit_id'), table_name='election_results')
    op.drop_index(op.f('ix_election_results_id'), table_name='election_results')
    op.drop_index(op.f('ix_election_results_election_id'), table_name='election_results')
    op.drop_index(op.f('ix_election_results_agent_id'), table_name='election_results')
    op.drop_table('election_results')
    op.drop_index(op.f('ix_election_constituencies_id'), table_name='election_constituencies')
    op.drop_index(op.f('ix_election_constituencies_election_id'), table_name='election_constituencies')
    op.drop_index(op.f('ix_election_constituencies_constituency_id'), table_name='election_constituencies')
    op.drop_table('election_constituencies')
    op.drop_index(op.f('ix_constituency_lgas_lga_id'), table_name='constituency_lgas')
    op.drop_index(op.f('ix_constituency_lgas_id'), table_name='constituency_lgas')
    op.drop_index(op.f('ix_constituency_lgas_constituency_id'), table_name='constituency_lgas')
    op.drop_table('constituency_lgas')
    op.drop_index(op.f('ix_candidates_party_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_election_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_constituency_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_candidate_code'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_parties_name'), table_name='parties')
    op.drop_index(op.f('ix_parties_id'), table_name='parties')
    op.drop_index(op.f('ix_parties_abbreviation'), table_name='parties')
    op.drop_table('parties')
    op.drop_index(op.f('ix_elections_status'), table_name='elections')
    op.drop_index(op.f('ix_elections_id'), table_name='elections')
    op.drop_index(op.f('ix_elections_election_year'), table_name='elections')
    op.drop_index(op.f('ix_elections_election_type'), table_name='elections')
    op.drop_table('elections')
    op.drop_index(op.f('ix_constituencies_name'), table_name='constituencies')
    op.drop_index(op.f('ix_constituencies_id'), table_name='constituencies')
    op.drop_index(op.f('ix_constituencies_constituency_type'), table_name='constituencies')
    op.drop_index(op.f('ix_constituencies_code'), table_name='constituencies')
    op.drop_table('constituencies')
    # ### end Alembic commands ###
