"""add election agent assignments

Revision ID: 97345eb645cb
Revises: 928be68b7f82
Create Date: 2026-09-25 12:09:49.466514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97345eb645cb'
down_revision: Union[str, Sequence[str], None] = '928be68b7f82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('election_agent_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('polling_unit_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['polling_unit_id'], ['polling_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('election_id', 'agent_id', 'polling_unit_id', name='uq_election_agent_pu_assignment')
    )
    op.create_index(op.f('ix_election_agent_assignments_agent_id'), 'election_agent_assignments', ['agent_id'], unique=False)
    op.create_index(op.f('ix_election_agent_assignments_election_id'), 'election_agent_assignments', ['election_id'], unique=False)
    op.create_index(op.f('ix_election_agent_assignments_id'), 'election_agent_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_election_agent_assignments_is_active'), 'election_agent_assignments', ['is_active'], unique=False)
    op.create_index(op.f('ix_election_agent_assignments_polling_unit_id'), 'election_agent_assignments', ['polling_unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_election_agent_assignments_polling_unit_id'), table_name='election_agent_assignments')
    op.drop_index(op.f('ix_election_agent_assignments_is_active'), table_name='election_agent_assignments')
    op.drop_index(op.f('ix_election_agent_assignments_id'), table_name='election_agent_assignments')
    op.drop_index(op.f('ix_election_agent_assignments_election_id'), table_name='election_agent_assignments')
    op.drop_index(op.f('ix_election_agent_assignments_agent_id'), table_name='election_agent_assignments')
    op.drop_table('election_agent_assignments')
    # ### end Alembic commands ###
